export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';
export const FETCH_FOLLOWERS_ON_REQUEST = 'FETCH_FOLLOWERS_ON_REQUEST';
export const FETCH_FOLLOWERS_ON_ERROR = 'FETCH_FOLLOWERS_ON_ERROR';
export const FETCH_USER = 'FETCH_USER';
